name: bus_o_pedia
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_nav_bar: ^5.0.6
  flutter_typeahead: ^5.2.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  dots_indicator: ^3.0.0
  url_launcher: ^6.0.20
  shimmer: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/north/
    - assets/images/south/
    - assets/images/contacts/
